apiVersion: v1
kind: Service
metadata:
  name: spring-argocd-app
spec:
  selector:
    app: spring-argocd-app
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
      nodePort: 30012
  type: NodePort